local BulletsData = {
	["9mm"] = {
		name = "9mm",
		Icon = "rbxassetid://116575917819443",
		Damage = 20,
		Range = 150,
		HeadshotMultiplier = 2.0
	},
	["5.56mm"] = {
		name = "5.56mm",
		Icon = "rbxassetid://...",
		Damage = 35,
		Range = 250,
		HeadshotMultiplier = 1.5
	},
	["12ga"] = {
		name = "12 Gauge",
		Icon = "rbxassetid://...",
		Damage = 60,
		Range = 50,
		HeadshotMultiplier = 1.2
	},
	["Rockets"] = {
		name = "Rockets",
		Icon = "rbxassetid://...",
		Damage = 150,
		Range = 300,
		HeadshotMultiplier = 1.0
	},
	["7.62mm"] = {
		name = "7.62mm",
		Icon = "rbxassetid://...",
		Damage = 100,
		Range = 500,
		HeadshotMultiplier = 2.0
	},
	["None"] = {
		name = "Knife",
		Icon = "rbxassetid://...",
		Damage = 25,
		Range = 5,
		HeadshotMultiplier = 1.0
	},
}

return BulletsData